import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import SessionProviderWrapper from "@/utils/sessionProviderWrapper";
//import AuthStatus from "@/components/authStatus";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <SessionProviderWrapper>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
       {/*  <AuthStatus /> */}
          <div className="flex h-screen w-full">
            <Sidebar />
            <div className="flex-1 w-full">
              <Navbar />
              <main className="p-4">{children}</main>
            </div>
          </div>


      </body>
    </html>
    </SessionProviderWrapper>
  );
}
